// Products contants
export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAIL = "GET_LIST_PRODUCT_FAIL";

export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAIL = "GET_DETAIL_PRODUCT_FAIL";

//Categories constants
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

//banner constants
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";

//language constants
export const SWITCH_LANG = "SWITCH_LANG";

//promotion constants
export const GET_PROMOTION_LIST = "GET_PROMOTION_LIST";
export const GET_PROMOTION_LIST_SUCCESS = "GET_PROMOTION_LIST_SUCCESS";
export const GET_PROMOTION_LIST_FAIL = "GET_PROMOTION_LIST_FAIL";

export const GET_DETAIL_PROMOTION = "GET_DETAIL_PROMOTION";
export const GET_DETAIL_PROMOTION_SUCCESS = "GET_DETAIL_PROMOTION_SUCCESS";
export const GET_DETAIL_PROMOTION_FAIL = "GET_DETAIL_PROMOTION_FAIL";
